services:
  web:
    image: ostis/sc-web:0.9.0
    build:
      context: ./interface/sc-web
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - sc-machine
    command:
      - "--server-host=machine"
    depends_on:
      machine:
        condition: service_healthy

  machine:
    image: ostis/sc-machine:0.10.0
    build:
      context: ./
    restart: unless-stopped
    volumes:
      # TODO(NikitaZotov): Don't load all project sources to volume to build knowledge-base.
      - ./:/knowledge-base
      - kb-binary:/kb.bin
    networks:
      - sc-machine
    ports:
      - "8090:8090"
    healthcheck:
      test: "/bin/bash -c 'source /app/.venv/bin/activate && python3 /app/scripts/healthcheck.py'"
      interval: 5s
      timeout: 10s
      retries: 3
      # start_period: 120s
    environment:
      # Use the commented env variable if you need to rebuild KB every startup. Also, use commented start period.
      #- "REBUILD_KB=1"
      - "KB_PATH=/knowledge-base/repo.path"
      - "BINARY_PATH=/app/sc-machine/bin"
      - "CONFIG_PATH=/knowledge-base/ostis-legislation.ini"
      - "EXTENSIONS_PATH=/app/build/Release/extensions;/app/sc-machine/lib/extensions"
      - "SC_SERVER_HOST=0.0.0.0"
    command:
      - "run"

volumes:
  kb-binary: {}

networks:
  sc-machine: {}
